### ISSUE TITLE
Publish initial project

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#1]
branch template:
`acronym/ticket-number-ticket-name`

example:
`kma/1-inital-project`

- [x] update libraries
- [x] add BOM for compose
- [x] fix theme warning

**Comment by MarekMacko** [comment]
Try to find out how to connect automatically issues with commit message/branch

**Comment by kmaslowiec** [comment]
- [ ] update libraries
- [ ] add BOM for compose
- [ ] fix theme warning

**Comment by kmaslowiec** [comment]
Not sure if we want to do that? 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message

We can also do this magic:
[video](https://www.google.com/search?q=how+to+use+tasks+and+context+with+github+with+android+studio&rlz=1C1CHBD_plPL871PL871&sxsrf=AJOqlzW6JMa6ScrdDfZrhjrgRwNVBNr1vA%3A1673100634790&ei=Wn25Y9PoL4OtrgTMrqnwBQ&ved=0ahUKEwjT_YnI0bX8AhWDlosKHUxXCl4Q4dUDCA8&uact=5&oq=how+to+use+tasks+and+context+with+github+with+android+studio&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQogQyBwgAEB4QogQyBQgAEKIEOgoIABBHENYEELADOgUIIRCgAToECCEQFToICCEQFhAeEB06BwghEKABEApKBAhBGABKBAhGGABQhQxYjyVg1yZoA3AAeACAAaABiAHMEZIBBDQuMTaYAQCgAQHIAQjAAQE&sclient=gws-wiz-serp#fpstate=ive&vld=cid:1e2a752c,vid:ntQJQEWOL10l)


THIS IS THE WAY: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
