### ISSUE TITLE
Handle FirebaseAuthRecentLoginRequiredException when deleting an account

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#100]
When the user authenticated into the app some time ago the delete account functionality did not work and is crashing the app because Firebase is throwing `FirebaseAuthRecentLoginRequiredException`:
```
com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.
```
To support account deletion using Firebase Auth we need to redirect the user to log in again before deleting an account.

**Comment by MarekMacko** [comment]
@BorysChajdas  Please close it if there is nothing to do anymore
