### ISSUE TITLE
Choose test framework for the app

### ISSUE THREAD

**Issue by marcinWisnia** [Android-Guild/Picover#14]
Junit or kotest ? or maybe something else :)

**Comment by kmaslowiec** [comment]
https://knapsackpro.com/testing_frameworks/difference_between/kotest/vs/junit

I think we all have worked already with JUnit so I would suggest Kotest.

**Comment by michal-kucznerowicz** [comment]
I would also go for Kotest

**Comment by BorysChajdas** [comment]
Any alternatives? If someone has some proposition other than Kotest + mockk then please leave a comment. Otherwise, we will use Kotest + mockk. Decision till 02.02.23.

**Comment by BorysChajdas** [comment]
Some other options: spek, junit

**Comment by MarekMacko** [comment]
+1 Kotest

**Comment by BorysChajdas** [comment]
Kotest won! I'll create a ticket to setup Kotest.
