### ISSUE TITLE
Update Read Me

### ISSUE THREAD

**Issue by kmaslowiec** [Android-Guild/Picover#180]
PR 

We do not cover all of the scenarios, focus on feature,s not on code perfection. 
Leave to do if something is not covered and known in advance. - create issue (optional)

**Comment by MarekMacko** [comment]
@kmaslowiec Is there anything left to do? Probably it can be closed

**Comment by kmaslowiec** [comment]
> @kmaslowiec Is there anything left to do? Probably it can be closed

Nope. Is done. Issue Closed. Than you.
