### ISSUE TITLE
Cleanup SignInIntentBuilder.Configuration

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#189]
Is there really a need to keep `Configuration.themeId` extracted?
1. it's used in one place
2. `.setTheme(R.style.Theme_Picover)` is self explanatory, keeping it extracted adds just more noise

**Comment by BorysChajdas** [comment]
@MarekMacko It's done like that for consistency, as providers are extracted to separate objects for me it's cleaner to keep all configuration related to sign-in intent in this object.
1. Providers are also used only in one place.
2. In my opinion it doesn't add more noise – all the configuration is stored in a configuration object and can be read from top to bottom.

Of course, we can just inline it but then some configurations will be extracted and some not. For me both solutions are OK but I prefer the existing one

**Comment by MarekMacko** [comment]
@BorysChajdas Of course it's not a big issue bug but imagine when someone would need to set additional properties. Another developer will follow existing approach and will extract these new properties as well, that would lead to totally redundant extraction, like below:
![image](https://github.com/intive/Picover/assets/12697488/68d702d0-7c3b-4847-8f14-569ea1080eea)

We can say "keep it extracted to follow consistency or because it's good practice" - but consistency and good practices are used to help understand the code and make it easier, without jumping throughout the file, to determine what is the value. In this case, builder method names are self explanatory. 

Let me know what you think to decide what to do with the ticket.

**Comment by BorysChajdas** [comment]
For me, in this case, such redundant extraction is OK – when you want to check the configuration you need to look at the `Configuration` object. But I also understand your point of view that we should only extract "more complicated" things because this way most of the configuration will be known only by looking at the `build` function. Let's say I'm convicted ;) I will handle this issue.

**Comment by MarekMacko** [comment]
The main point to show rest of the temat, that we don't have to extract it every time 😄

**Comment by MarekMacko** [comment]
Please read the discussion and unassign yourself as a confirmation
