### ISSUE TITLE
Avoid tight coupling 

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#195]
Internal implementation shouldn't be aware of its outside usage. It should be separated and not coupled, this rule applies for the naming as well. 
Let's take a below example, `openDetails` directly suggest what action should be performed, but it's a responsibility of external component. If we would like to play a video or send tracking event on click, then we would need to change a name to not confuse rest of the team. Trivial thing but can involve to really confusing thing.  
```
@Composable
private fun PartyTile(
    party: Party,
    openDetails: (Int) -> Unit,
) {
    Card(
        modifier = Modifier.clickable {	
            openDetails(party.id)
	},
   ....
```

**Comment by MarekMacko** [comment]
@BorysChajdas @kmaslowiec @marcinWisnia @michal-kucznerowicz Please read the description and unassign yourself if everything it's clear. 
After that, someone needs to pick up the issue and just rename `openDetails` parameter

**Comment by kmaslowiec** [comment]
> @BorysChajdas @kmaslowiec @marcinWisnia @michal-kucznerowicz Please read the description and unassign yourself if everything it's clear. After that, someone needs to pick up the issue and just rename `openDetails` parameter

@MarekMacko @marcinWisnia Understood. I think we can correct it within our current task. Thank you.

**Comment by michal-kucznerowicz** [comment]
Interesting one. I've never looked at naming this way
