### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#2]
Include: 
branch template:
acronym/ticket-number-ticket-name

example:
kma/1-inital-project

**Comment by Nataniel-Antosik** [comment]
**SUGGESTION:**
Maybe not now but in a near future we could add all members to readme with images and nicknames for example:
```
<p>
  <figure class="image" >
    <a href="https://github.com/nickname">
      <img src="https://avatars.githubusercontent.com/nickname" alt="name surname" width="70">
      <figcaption>name surname</figcaption>
    </a>
  </figure>
</p>
```
