### ISSUE TITLE
Rename openDetails to avoid tight coupling

### ISSUE THREAD

**Issue by kmaslowiec** [Android-Guild/Picover#257]

**Comment by MarekMacko** [comment]
@kmaslowiec Could you describe what is the scope of this issue? Isn't the same as for #195 ?

**Comment by kmaslowiec** [comment]
> @kmaslowiec Could you describe what is the scope of this issue? Isn't the same as for #195 ? Long story short, it is not necessary.
Long story short, it is not necessary.
