### ISSUE TITLE
Profile screen stays when orientation is change from horizontal to vertical

### ISSUE THREAD

**Issue by kmaslowiec** [Android-Guild/Picover#288]
Reproduction: 
- open an app in horizontal orientation
- click on Profile
- change orientation to vertical

**Current behavior:**
The profile screen is shown and also the profile in drawer:

https://github.com/intive/Picover/assets/33199010/3ce56d22-c555-4369-96be-a36de7c37258

**Expected behavior:** In vertical orientation, the screen should show the previous screen and the Profile should be in a drawer only.

**Comment by MarekMacko** [comment]
Solved by #294. @kmaslowiec Feel free to reopen the issue if it appears again
