### ISSUE TITLE
User should not be able to enter more signs that limited by the text validator

### ISSUE THREAD

**Issue by kmaslowiec** [Android-Guild/Picover#297]
Reproduction:
- open any component that has an editable text field

Expected behavior: 
- a user should not be able to enter more signs than limited by the text validator

Current behavior: 
- a user only gets the error message but still can write as many signs as he wants. 

https://github.com/Android-Guild/Picover/assets/33199010/68093b3f-ce8a-4f05-a753-714bc3d50648

**Comment by MarekMacko** [comment]
If you wan to prevent from entering more sings than it's restricted by validator, then error would never show up

**Comment by bartek977** [comment]
there should be rather character counter. I think we discussed it in the past, @michal-kucznerowicz

**Comment by MarekMacko** [comment]
> there should be rather character counter. I think we discussed it in the past, @michal-kucznerowicz

Fully agree

**Comment by kmaslowiec** [comment]
> If you wan to prevent from entering more sings than it's restricted by validator, then error would never show up

What if it would allow one more than the error? For example, the error shows on the 20th sign but you can write 21 signs.

**Comment by bartek977** [comment]
> > If you wan to prevent from entering more sings than it's restricted by validator, then error would never show up
> 
> What if it would allow one more than the error? For example, the error shows on the 20th sign but you can write 21 signs.

you mean, some field allow to write 21 characters? Then you can create new provider for your needs 

for example you have description field where user can put 250 characters, so the provider can look like this:
```
@Provides
@Validator.UserDescription
fun provideUserDescriptionValidator() =
	textValidator {
		allowEmpty = true
		allowBlank = false
		maxLength = 250
	}
```

**Comment by kmaslowiec** [comment]
> > > If you wan to prevent from entering more sings than it's restricted by validator, then error would never show up
> > 
> > 
> > What if it would allow one more than the error? For example, the error shows on the 20th sign but you can write 21 signs.
> 
> you mean, some field allow to write 21 characters? Then you can create new provider for your needs
> 
> for example you have description field where user can put 250 characters, so the provider can look like this:
> 
> ```
> @Provides
> @Validator.UserDescription
> fun provideUserDescriptionValidator() =
> 	textValidator {
> 		allowEmpty = true
> 		allowBlank = false
> 		maxLength = 250
> 	}
> ```

How does that prevents the user from typing the signs?

**Comment by bartek977** [comment]
if you don't want user typing signs you should extend `TextValidator` :)

**Comment by MarekMacko** [comment]
@michal-kucznerowicz Please post your findings from the guidelines

**Comment by michal-kucznerowicz** [comment]
There are no official guidelines for text field validation. I've found only best practices posted by UX designers on blogs that it is better to allow users to type more characters than allowed and allow them to decide by themselves how to fit max size, instead of disallowing them to type more than the limit. I would suggest to leave it as is.

**Comment by kmaslowiec** [comment]
> There are no official guidelines for text field validation. I've found only best practices posted by UX designers on blogs that it is better to allow users to type more characters than allowed and allow them to decide by themselves how to fit max size, instead of disallowing them to type more than the limit. I would suggest to leave it as is.

@MarekMacko @bartek977 @BorysChajdas @marcinWisnia Please give a sign if you agree so I can close the issue. Also please advise regarding #319

**Comment by MarekMacko** [comment]
Actually I had the same opinion as @michal-kucznerowicz posted so nothing changes on my side. 
I think it is reasonable to add some section in README e.g. "agreements" and describe our approach for validation, especially for future discussions. Let me know what you think guys.

**Comment by kmaslowiec** [comment]
> Actually I had the same opinion as @michal-kucznerowicz posted so nothing changes on my side. I think it is reasonable to add some section in README e.g. "agreements" and describe our approach for validation, especially for future discussions. Let me know what you think guys.

@MarekMacko I agree. How about the rest? @bartek977 @michal-kucznerowicz @BorysChajdas @marcinWisnia

**Comment by BorysChajdas** [comment]
Same as @michal-kucznerowicz

**Comment by marcinWisnia** [comment]
@michal-kucznerowicz approach convinced me as well :)

**Comment by bartek977** [comment]
agreed with @michal-kucznerowicz approach

**Comment by kmaslowiec** [comment]
ReadMe updated in: #343

**Comment by kmaslowiec** [comment]
ReadMe updated in: https://github.com/Android-Guild/Picover/issues/343
