### ISSUE TITLE
Provide MVI tutorial

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#3]

**Comment by MarekMacko** [comment]
https://www.youtube.com/watch?v=1vlTPp336UY

**Comment by kmaslowiec** [comment]
https://stackoverflow.com/questions/59205614/what-is-the-difference-between-mvi-compared-to-mvc-and-mvvm

http://androidcode.pl/blog/wzorce/mvi/

https://medium.com/swlh/mvi-architecture-with-android-fcde123e3c4a#:~:text=MVI%20stands%20for,the%20app%20itself.

https://github.com/sockeqwe/mosby

**Comment by michal-kucznerowicz** [comment]
https://www.youtube.com/watch?v=E6obYmkkdko
https://www.youtube.com/watch?v=DGSihxSVdfc
