### ISSUE TITLE
Agreements section in ReadMe and text validation

### ISSUE THREAD

**Issue by kmaslowiec** [Android-Guild/Picover#343]
Please see: https://github.com/Android-Guild/Picover/issues/297#issuecomment-1761391812

**Comment by kmaslowiec** [comment]
Does anybody have ideas for more agreements that can be added to the ReadMe?
@marcinWisnia @MarekMacko @BorysChajdas @bartek977 @michal-kucznerowicz 

The one that i have is: Text validation: allow users to type more characters than limited by the validator and let them to decide how to fit the signs to match the max size. See discussion: #297

**Comment by michal-kucznerowicz** [comment]
Have no more ideas

**Comment by MarekMacko** [comment]
Nothing comes to my mind but let's use this as a starting point for future agreements :)
