### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#4]
- [ ] build debug

**Comment by MarekMacko** [comment]
- master: `build`
- develop: `build` 
- pull request: `build`

**Comment by Nataniel-Antosik** [comment]
SUGGESTION:
When CI was ready and working correctly and we will have a readme. We could add to the readme **Status badge** this option is in _Actions > concrete workflow >  3 dot menu > Create status badge_. It is to show if currently PR or master is working correctly it looks like this:  
![image](https://user-images.githubusercontent.com/57491794/212348909-d925a477-b0db-45c0-871e-995ed4b51b78.png)

**Comment by kmaslowiec** [comment]
read list: INTRO
https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

https://ncorti.com/blog/howto-github-actions-building-android

Syntax o Github Action:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Example yaml file to start
https://github.com/actions/starter-workflows/tree/main/ci

More Advance
https://innovorder.dev/set-up-an-android-ci-using-github-actions-10ea8ed03bc5

**Comment by kmaslowiec** [comment]
@MarekMacko Can you please specify by this?


![Image](https://user-images.githubusercontent.com/33199010/212977573-8ebc7148-fff7-4a62-a5a6-9d3d09990205.png)

I wrote a workflow that checks the build for each Pull Request and when sth is pushed to 'dev' branch. We have discussed with @BorysChajdas that no master branch is required. 

Should I add any other step to the workflow? Please see #16

**Comment by kmaslowiec** [comment]
Fix bild from PR to Dev
