### ISSUE TITLE
Max line length in .editorconfig

### ISSUE THREAD

**Issue by Nataniel-Antosik** [Android-Guild/Picover#41]
We should discuss which length will be appropriate in the `.editorconfig` file. So I leave comments ranging from 100 to the current value with step 10 points. 

**IMPORTANT** If you agree with concrete value leave a heart below comment

**Comment by Nataniel-Antosik** [comment]
Current 180

**Comment by Nataniel-Antosik** [comment]
170

**Comment by Nataniel-Antosik** [comment]
160

**Comment by Nataniel-Antosik** [comment]
150

**Comment by Nataniel-Antosik** [comment]
140

**Comment by Nataniel-Antosik** [comment]
130

**Comment by Nataniel-Antosik** [comment]
120

**Comment by Nataniel-Antosik** [comment]
110

**Comment by Nataniel-Antosik** [comment]
100

**Comment by marcinWisnia** [comment]
I would go for 160 for normal files and 180 for tests files -> we have this set like that in our project and in my opinion it works really good.

**Comment by BorysChajdas** [comment]
Decided to go with 140 and 180 for tests.
