### ISSUE TITLE
Setup Firebase project

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#43]
- Create Firebase project
- Integrate with app (google-services.json)

**Comment by kmaslowiec** [comment]
Before I start working on it I have a few questions:

- Should I create a brand new Firebase account or do we have some Intive one that we can use?
- I suggest creating an e-mail for the project e.g. Picover2023@gmail.com. We can use it also for other accounts if necessary. Is it a good idea?
- Do we agree that JSON files should not be stored in github and we should keep it locally? Or should I research better-secured ways to do so?

Let me know guys, sooner the better.

**Comment by BorysChajdas** [comment]
1. Create a new Firebase project for us, if we encounter any limitations then we will look for some intive Firebase account.
2. Good idea to me!
3. Let's start with the basic approach (store it in GIT) and create some draft issue to discuss later.

**Comment by MarekMacko** [comment]
I would vote for more generic email, to not stick to exact year ;)

**Comment by kmaslowiec** [comment]
> 

I will do my best but let's see what is available :)

**Comment by kmaslowiec** [comment]
@MarekMacko I will do my best, but let's see what is available.
