### ISSUE TITLE
GitHub rule to force 2 approvers for all branches

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#53]
At this moment every pull requests which does not indicate on the dev branch, could be merged without any approvals, and check if the build has not failed.

**Comment by Nataniel-Antosik** [comment]
IMO it's done 

![Image](https://user-images.githubusercontent.com/57491794/219594607-d1d9a4e0-e683-4225-b502-7dbd4f8b6e16.png)

but someone could check this :D

Link: https://github.com/intive/Picover/settings/branches

**Comment by BorysChajdas** [comment]
@Nataniel-Antosik now there is no possibility to (force) push new changes to pull request :/

**Comment by BorysChajdas** [comment]
Looks like we need to find some other solution, I will remove it for now to not block pull requests

**Comment by Nataniel-Antosik** [comment]
Another link: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by Nataniel-Antosik** [comment]
@BorysChajdas It was a problem why we can't push to this. 
![image](https://user-images.githubusercontent.com/57491794/220555405-fe087f99-550d-4b3b-a94e-786ad9204d8c.png)

**Comment by Nataniel-Antosik** [comment]
@BorysChajdas Could you look again at my changes :D
