### ISSUE TITLE
Parties screen

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#54]
Parties should be on the main screen of the app.

Icon for the screen on bottom navigation: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:celebration:FILL@0;wght@400;GRAD@0;opsz@48&icon.platform=android

- List of parties, for now, parties will be stored locally
- Component to add new party (FAB, button, or something else)

Party:
- For now only the tile with the title and description
- Tile should be clickable
- After clicking on the tile we should navigate to a new screen – party details, party should be passed as an argument

Party details:
- Should display the title and description of the party

**Comment by MarekMacko** [comment]
- [x] List of parties, for now, parties will be stored locally,
- [ ] Component to add new party (FAB, button, or something else)
- [x] For now only the tile with the title and description,
- [x] Tile should be clickable,
- [x] After clicking on the tile we should navigate to a new screen – party details, party should be passed as an argument
- [x] Should display the title and description of the party

Seems that FAB is the missing part to close the issue?
