### ISSUE TITLE
Presentation for people from the Szczecin office

### ISSUE THREAD

**Issue by Nataniel-Antosik** [Android-Guild/Picover#58]
## Description: 
Recently @MarekMacko mention preparing presentations for other people than just us. The first step will be a presentation for Intive members from Szczecin. 

### How it will work?
Anybody who would like to make a presentation about any topic from Android should leave a comment below with e.g. "_I am interested_" and with your idea. If you don't have it we could together discuss this and found something. 

### How the presentation could look like?
First, we estimate possible how long does the presentation last (up to 5 minutes). The topic doesn't have to be very detailed it can be just a snippet of more complicated things or just a simple thing/topic. For example, if you show a new approach to something old you can show the advantages and disadvantages of this and what is this for someone who doesn't know it.

## List who wants to make a presentation:
@MarekMacko, **topic**: Custom Lint Rule
@Nataniel-Antosik, **topic**: Splash screen
@bartek977, **topic**: Comparison of MVP and MVVM with examples
@marcinWisnia , **topic**: - Introduction to Kotest property testing
@michal-kucznerowicz, **topic**: Praca inżynierska - "Aplikacja do wspierania badań nad estetyką sklepów internetowych"
@kmaslowiec, **topic**: - Bald and Old - What I learned when I started coding after my 30s
@BorysChajdas, **topic**: - Simple widget using Jetpack Glance

**Comment by BorysChajdas** [comment]
@MarekMacko upload template
