### ISSUE TITLE
Revoke current google-services.json and use a new one

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#95]
Try to generate new google-services.json from Firebase and replace with existing one to Github secrets

https://console.firebase.google.com/u/0/project/picover-6590c/settings/general/android:com.intive.picover

**Comment by MarekMacko** [comment]
@bartek977  Please post here your findings

**Comment by bartek977** [comment]
I didn't find a way to regenerate google-services.json file. I've tried removing the app from firebase project and creating a new one with the same values (package name & app nickname) but the result file had the same content. Probably changing package will solve the problem

**Comment by MarekMacko** [comment]
I've removed old Web Api Key and generated the new one. 
You need to download new `google-services.json` to make app work back.
Source: https://stackoverflow.com/a/44896098/10894077

**Comment by bartek977** [comment]
I will handle it when the project will be fixed (right now I don't have access to our secrets)

**Comment by MarekMacko** [comment]
> I will handle it when the project will be fixed (right now I don't have access to our secrets)

What fix you're referring to?

**Comment by bartek977** [comment]
access to the repo

**Comment by MarekMacko** [comment]
> access to the repo

But what you want to fix? We don't keep `google.services` in the repository

**Comment by bartek977** [comment]
but the file is stored in secrets on github where I don't have access right now

**Comment by MarekMacko** [comment]
@bartek977 You're unblocked

**Comment by bartek977** [comment]
Done
